### ISSUE TITLE
isspace() is not complete

### ISSUE THREAD

**Issue by cinaryilmaz** [Akif9748/node-interpreter#1]
Current `isspace` function only looks for `' '` (space) character while it should look for all these characters: `'\t'`, `'\n'`, `'\r'`, `'\v'`, `'\f'`, `' '`

**Comment by cinaryilmaz** [comment]
I mean something like this function: https://opensource.apple.com/source/BerkeleyDB/BerkeleyDB-18/db/clib/isspace.c.auto.html

**Comment by Akif9748** [comment]
node-interpreter is deprecated, but we will look for this, thanks
